In [12]:
import numpy as np
import numdifftools as nd
from functions import himmelblau

In [23]:
x = [0.0,0.0]
x0 = [2.0, 3.0]

In [16]:
df = nd.Gradient(himmelblau)
f_hessian = nd.Hessian(himmelblau)(x)


In [29]:
df(x0)

array([-24.,  40.])

In [32]:
pk = -df(x) + (np.dot(np.transpose(df(x) - df(x0)), df(x)) / np.dot(np.transpose(df(x0)), df(x0)))*df(x0)


In [33]:
pk

array([ 0.5, 44.5])

In [5]:
f_hessian

array([[-42.,   0.],
       [  0., -26.]])

In [6]:
epsilon = 0.001
identity_matrix = np.eye(len(x)) * epsilon
identity_matrix

array([[0.001, 0.   ],
       [0.   , 0.001]])

In [7]:
f_hessian_modified = f_hessian + identity_matrix
f_hessian_modified

array([[-41.999,   0.   ],
       [  0.   , -25.999]])

In [8]:
f_hessian_inv = np.linalg.inv(f_hessian)
f_hessian_inv

array([[-0.02380952, -0.        ],
       [-0.        , -0.03846154]])

In [9]:
-np.dot(f_hessian_inv, df)

array([-0.33333333, -0.84615385])

In [10]:
pk = -np.linalg.solve(f_hessian, df)

In [11]:
pk

array([-0.33333333, -0.84615385])

In [33]:
grad = nd.Gradient(himmelblau)

In [34]:
grad([1,1])

array([-46., -38.])

### Função de Rosenbrock

In [32]:
def rosen(x): 
    return (1-x[0])**2 + 105.*(x[1]-x[0]**2)**2

In [43]:
np.array([0.65, 0.78])

array([0.65, 0.78])

In [48]:
np.any(np.array([0.70, 0.5]) <= 0.6, axis=0)

True

In [35]:
np.all([[0.14, 0.22],[1e-06, 1e-06]])

True

In [56]:
print((np.array([0.14, 0.22]) < 1e-06).all())   

False
