In [6]:
import numpy as np
import numdifftools as nd
from functions import himmelblau

In [9]:
x = [0.0,0.0]

In [19]:
df = nd.Gradient(himmelblau)(x)
f_hessian = nd.Hessian(himmelblau)(x)


In [24]:
df

array([-14., -22.])

In [20]:
f_hessian

array([[-42.,   0.],
       [  0., -26.]])

In [21]:
f_hessian_inv = np.linalg.inv(f_hessian)
f_hessian_inv

array([[-0.02380952, -0.        ],
       [-0.        , -0.03846154]])

In [23]:
-np.dot(f_hessian_inv, df)

array([-0.33333333, -0.84615385])

In [11]:
pk = -np.linalg.solve(f_hessian, df)

In [12]:
pk

array([-0.33333333, -0.84615385])

In [24]:
def himmelblau_gradient(x, y):
    df_dx = 2 * (x**2 + y - 11) * (2 * x) + 2 * (x + y**2 - 7)
    df_dy = 2 * (x**2 + y - 11) + 2 * (x + y**2 - 7) * (2 * y)
    d = [df_dx, df_dy]
    return d

# Testando o vetor gradiente em um ponto específico, por exemplo, (1, 1)
gradient_at_1_1 = himmelblau_gradient(1, 1)
print("Gradient at (1, 1):", gradient_at_1_1)


Gradient at (1, 1): [-46, -38]


In [33]:
grad = nd.Gradient(himmelblau)

In [34]:
grad([1,1])

array([-46., -38.])

### Função de Rosenbrock

In [32]:
def rosen(x): 
    return (1-x[0])**2 + 105.*(x[1]-x[0]**2)**2

In [43]:
np.array([0.65, 0.78])

array([0.65, 0.78])

In [48]:
np.any(np.array([0.70, 0.5]) <= 0.6, axis=0)

True

In [35]:
np.all([[0.14, 0.22],[1e-06, 1e-06]])

True

In [56]:
print((np.array([0.14, 0.22]) < 1e-06).all())   

False
